sudo: true
language: ruby
rvm:
  - 2.3.1
before_script:
  - sudo ln /dev/null /dev/raw1394
script:
  - bundle exec rubocop
  - bundle exec rake build --trace
  - bundle exec rake test --trace
addons:
  apt:
    packages:
      - g++-6
      - cmake
      - cmake-data
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports