sudo: required
dist: trusty
group: stable
language: ruby
rvm:
  - 2.3.1
cache: bundler
before_script:
  - sudo ln /dev/null /dev/raw1394
script:
  - ./build-ext
  - bundle exec rake test
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - cmake-data
      - g++-6
      - libwebp-dev
      - libx264-dev
      - nasm
      - yasm
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
