sudo: required
dist: trusty
group: stable
language: ruby
rvm:
  - 2.3.1
cache: bundler
before_script:
  - sudo ln /dev/null /dev/raw1394
script:
  - ./build-test
addons:
  apt:
    packages:
      - build-essential
      - g++-6
      - cmake
      - cmake-data
      - nasm
      - yasm
      - libwebp-dev
      - libx264-dev
      - libvpx-dev
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
