sudo: false
language: ruby
rvm:
  - 2.3.1
script:
  - cd ./ext/nuvo_image
  - cmake .
  - make
addons:
  apt:
    packages:
      - cpp-6
      - cmake
      - cmake-data
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports