sudo: false
language: ruby
rvm:
  - 2.3.1
cache:
  directories:
  - vendor/bundle
script:
  - bundle install
  - bundle exec rubocop
  - bundle exec rake install
  - bundle exec rake test
addons:
  apt:
    packages:
      - gcc-6-base
      - g++-6
      - cmake
      - libopencv-core2.4
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake